# Copyright 2025 The Astra Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui/views/views.gni")

component("astra_tab_context_menu_views") {
  sources = [
    "astra_tab_context_menu_view.cc",
    "astra_tab_context_menu_view.h",
  ]

  defines = [ "ASTRA_TAB_CONTEXT_MENU_VIEWS_IMPLEMENTATION" ]

  deps = [
    "//base",
    "//skia",
    "//ui/base",
    "//ui/gfx",
    "//ui/views",
    "//ui/views/bubble",
    "//ui/views/controls",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "astra_tab_context_menu_views_unittest.cc",
  ]

  deps = [
    ":astra_tab_context_menu_views",
    "//base",
    "//base/test:test_support",
    "//testing/gtest",
    "//ui/views:views_test_support",
  ]
}
