import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = join(__dirname, "..");

describe("sidebar component structure", () => {
  it("keeps cross-section sidebar menu chrome in the common component layer", () => {
    const commonMenuItemPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarMenuItem.tsx");
    const commonMenuSurfacePath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarMenuSurface.tsx");
    const commonItemActionHintsPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarItemActionHints.tsx");
    const commonItemIconPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarItemIcon.tsx");
    const commonModifierHintsPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarModifierActionHints.tsx");
    const commonSectionHeaderPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarSectionHeader.tsx");
    const commonTabStatusBadgesPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarTabStatusBadges.tsx");
    const menuDismissalPath = join(root, "src/renderer/common/context-menu/menuDismissal.ts");
    const oldTabsActionHintsPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarItemActionHints.tsx");
    const oldTabsItemIconPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarItemIcon.tsx");
    const oldTabsMenuItemPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarMenuItem.tsx");
    const oldTabsStatusBadgesPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarTabStatusBadges.tsx");
    const sidebarMenuCssPath = join(root, "src/renderer/styles/sidebar-menu.css");
    const stylesEntry = readFileSync(join(root, "src/renderer/styles.css"), "utf8");
    const commonMenuItem = readFileSync(commonMenuItemPath, "utf8");
    const commonMenuSurface = readFileSync(commonMenuSurfacePath, "utf8");
    const commonItemActionHints = readFileSync(commonItemActionHintsPath, "utf8");
    const commonItemIcon = readFileSync(commonItemIconPath, "utf8");
    const commonModifierHints = readFileSync(commonModifierHintsPath, "utf8");
    const commonSectionHeader = readFileSync(commonSectionHeaderPath, "utf8");
    const commonTabStatusBadges = readFileSync(commonTabStatusBadgesPath, "utf8");
    const menuDismissal = readFileSync(menuDismissalPath, "utf8");
    const sidebarRowReorderDrop = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarRowReorderDrop.ts"), "utf8");
    const workspaceStrip = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/workspaces/WorkspaceStrip.tsx"), "utf8");
    const sidebarWorkspaceDropIntent = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarWorkspaceDropIntent.ts"), "utf8");
    const sidebarQuickEntryReorderDrop = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarQuickEntryReorderDrop.ts"), "utf8");
    const sidebarQuickEntryDragHook = readFileSync(join(root, "src/renderer/surfaces/sidebar/hooks/useSidebarQuickEntryDrag.ts"), "utf8");
    const sidebarItems = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarItems.tsx"), "utf8");
    const sidebarPinnedTabs = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarPinnedTabs.tsx"), "utf8");
    const sidebarClosedTabButton = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/ClosedTabButton.tsx"), "utf8");
    const sidebarItemActivation = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarItemActivation.ts"), "utf8");
    const sidebarTabGroupHeaderDrop = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarTabGroupHeaderDrop.ts"), "utf8");
    const sidebarSections = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarSections.tsx"), "utf8");
    const sidebarTabsSection = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarTabsSection.tsx"), "utf8");
    const tabGroupSection = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/TabGroupSection.tsx"), "utf8");
    const sidebarSearchBox = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/chrome/SidebarSearchBox.tsx"), "utf8");
    const sidebarContextMenusHook = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/useSidebarContextMenus.ts"), "utf8");
    const anchoredContextMenuHook = readFileSync(join(root, "src/renderer/common/context-menu/useAnchoredContextMenu.ts"), "utf8");
    const tabGroupContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/TabGroupContextMenu.tsx"), "utf8");
    const tabContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/TabContextMenu.tsx"), "utf8");
    const quickEntryContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/QuickEntryContextMenu.tsx"), "utf8");
    const closedTabContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/ClosedTabContextMenu.tsx"), "utf8");
    const sidebarSplitDropTarget = readFileSync(join(root, "src/renderer/surfaces/sidebar/model/sidebarSplitDropTarget.ts"), "utf8");
    const sidebarMenuCss = readFileSync(sidebarMenuCssPath, "utf8");
    const workspaceCss = readFileSync(join(root, "src/renderer/styles/sidebar-workspaces.css"), "utf8");
    const tabContextMenuCss = readFileSync(join(root, "src/renderer/styles/sidebar-context-menu.css"), "utf8");

    expect(existsSync(commonMenuItemPath)).toBe(true);
    expect(existsSync(commonMenuSurfacePath)).toBe(true);
    expect(existsSync(commonItemActionHintsPath)).toBe(true);
    expect(existsSync(commonItemIconPath)).toBe(true);
    expect(existsSync(commonModifierHintsPath)).toBe(true);
    expect(existsSync(commonSectionHeaderPath)).toBe(true);
    expect(existsSync(commonTabStatusBadgesPath)).toBe(true);
    expect(existsSync(menuDismissalPath)).toBe(true);
    expect(existsSync(oldTabsActionHintsPath)).toBe(false);
    expect(existsSync(oldTabsItemIconPath)).toBe(false);
    expect(existsSync(oldTabsMenuItemPath)).toBe(false);
    expect(existsSync(oldTabsStatusBadgesPath)).toBe(false);
    expect(existsSync(sidebarMenuCssPath)).toBe(true);
    expect(stylesEntry).toContain('@import "./styles/sidebar-menu.css";');
    expect(commonMenuItem).toContain("SidebarMenuSeparator");
    expect(commonMenuItem).not.toContain("tab-context-menu-separator");
    expect(commonMenuSurface).toContain("useMenuInitialFocus");
    expect(commonMenuSurface).toContain("handleMenuKeyboardNavigation");
    expect(commonMenuSurface).toContain('role="menu"');
    expect(commonMenuSurface).toContain("event.stopPropagation()");
    expect(commonItemActionHints).toContain("SidebarModifierActionHints");
    expect(commonItemIcon).toContain("BrowserItemIcon");
    expect(commonModifierHints).toContain("FiEye");
    expect(commonModifierHints).toContain("FiColumns");
    expect(commonModifierHints).toContain("getModifierActionHintsLabel");
    expect(commonModifierHints).toContain("data-sidebar-modifier-hints");
    expect(commonModifierHints).toContain("data-sidebar-modifier-hint");
    expect(commonSectionHeader).toContain("getDisclosureKeyboardToggleIntent");
    expect(commonSectionHeader).toContain("sidebar-section-header");
    expect(commonTabStatusBadges).toContain("data-sidebar-tab-status-badges");
    expect(commonTabStatusBadges).toContain("data-sidebar-tab-status-badge");
    expect(sidebarRowReorderDrop).toContain("acceptSidebarRowReorderDrag");
    expect(sidebarRowReorderDrop).toContain("resolveSidebarRowReorderDrop");
    expect(sidebarRowReorderDrop).toContain("clearSidebarRowReorderDrop");
    expect(sidebarItemActivation).toContain("getSidebarItemPointerActivation");
    expect(sidebarItemActivation).toContain("runSidebarItemPointerActivation");
    expect(menuDismissal).toContain("useContextMenuDismissal");
    expect(menuDismissal).toContain("useRef");
    expect(menuDismissal).toContain("restoreFocus: false");
    expect(menuDismissal).toContain("window.addEventListener(\"scroll\"");
    expect(workspaceStrip).toContain('from "../common/SidebarMenuItem"');
    expect(workspaceStrip).toContain('from "../common/SidebarMenuSurface"');
    expect(workspaceStrip).toContain("useContextMenuDismissal");
    expect(workspaceStrip).toContain("acceptSidebarRowReorderDrag");
    expect(workspaceStrip).toContain("clearSidebarRowReorderDrop");
    expect(workspaceStrip).toContain("acceptSidebarNewWorkspaceDropTarget");
    expect(workspaceStrip).not.toContain("getSidebarNewWorkspaceDropIntent");
    expect(sidebarWorkspaceDropIntent).toContain("acceptSidebarNewWorkspaceDropTarget");
    expect(sidebarWorkspaceDropIntent).toContain("getSidebarNewWorkspaceDropIntent");
    expect(workspaceStrip).not.toContain("readSidebarFavoriteDragId");
    expect(workspaceStrip).not.toContain("readSidebarTabDragEventId");
    expect(workspaceStrip).not.toContain("updateDropPlacement");
    expect(workspaceStrip).not.toContain("clearDropPlacement");
    expect(sidebarQuickEntryDragHook).toContain("resolveSidebarQuickEntryReorderDrop");
    expect(sidebarQuickEntryDragHook).not.toContain("readSidebarEssentialDragId");
    expect(sidebarQuickEntryDragHook).not.toContain("readSidebarFavoriteDragId");
    expect(sidebarQuickEntryDragHook).not.toContain("getPointerDropPlacement");
    expect(sidebarQuickEntryDragHook).not.toContain("runQuickEntryReorder");
    expect(sidebarQuickEntryReorderDrop).toContain("readSidebarEssentialDragId");
    expect(sidebarQuickEntryReorderDrop).toContain("readSidebarFavoriteDragId");
    expect(sidebarQuickEntryReorderDrop).toContain("getPointerDropPlacement");
    expect(sidebarItems).toContain('from "../common/SidebarItemActionHints"');
    expect(sidebarItems).toContain('from "../common/SidebarItemIcon"');
    expect(sidebarItems).toContain("runSidebarItemPointerActivation");
    expect(sidebarItems).toContain("acceptSidebarRowReorderDrag");
    expect(sidebarItems).toContain("resolveSidebarRowReorderDrop");
    expect(sidebarItems).not.toContain("updateDropPlacement");
    expect(sidebarItems).not.toContain("clearDropPlacement");
    expect(sidebarItems).not.toContain("event.altKey");
    expect(sidebarItems).not.toContain("event.shiftKey");
    expect(sidebarItems).not.toContain("export function SidebarSectionHeader");
    expect(sidebarPinnedTabs).toContain('from "../common/SidebarItemActionHints"');
    expect(sidebarPinnedTabs).toContain('from "../common/SidebarItemIcon"');
    expect(sidebarPinnedTabs).toContain('from "../common/SidebarSectionHeader"');
    expect(sidebarPinnedTabs).toContain("runSidebarItemPointerActivation");
    expect(sidebarPinnedTabs).toContain("acceptSidebarRowReorderDrag");
    expect(sidebarPinnedTabs).toContain("resolveSidebarRowReorderDrop");
    expect(sidebarPinnedTabs).not.toContain("updateDropPlacement");
    expect(sidebarPinnedTabs).not.toContain("clearDropPlacement");
    expect(sidebarPinnedTabs).not.toContain("event.altKey");
    expect(sidebarPinnedTabs).not.toContain("event.shiftKey");
    expect(sidebarClosedTabButton).toContain("runSidebarItemPointerActivation");
    expect(sidebarClosedTabButton).not.toContain("event.altKey");
    expect(sidebarClosedTabButton).not.toContain("event.shiftKey");
    expect(tabGroupSection).toContain("acceptSidebarTabGroupHeaderDrag");
    expect(tabGroupSection).toContain("resolveSidebarTabGroupHeaderDrop");
    expect(tabGroupSection).not.toContain("readSidebarTabDragEventId");
    expect(tabGroupSection).not.toContain("readSidebarGroupDragId");
    expect(sidebarTabGroupHeaderDrop).toContain("acceptSidebarRowReorderDrag");
    expect(sidebarTabGroupHeaderDrop).toContain("resolveSidebarRowReorderDrop");
    expect(sidebarTabGroupHeaderDrop).toContain("readSidebarTabDragId");
    expect(sidebarTabGroupHeaderDrop).toContain("readSidebarGroupDragId");
    expect(tabGroupSection).not.toContain("updateDropPlacement");
    expect(tabGroupSection).not.toContain("clearDropPlacement");
    expect(sidebarSections).toContain('from "../common/SidebarSectionHeader"');
    expect(sidebarSections).toContain('acceptSidebarTabFolderDrag(event, draggingTabId, "copy")');
    expect(sidebarSections).not.toContain("readSidebarTabDragEventId");
    expect(sidebarTabsSection).toContain('from "../common/SidebarSectionHeader"');
    expect(sidebarSearchBox).toContain("SidebarModifierActionHints");
    expect(sidebarSearchBox).not.toContain("FiEye");
    expect(sidebarSearchBox).not.toContain("FiColumns");
    expect(workspaceStrip).toContain("sidebar-more-menu");
    expect(sidebarSplitDropTarget).toContain("acceptSidebarSplitDropTarget");
    expect(sidebarSplitDropTarget).toContain("resolveSidebarSplitDrop");
    expect(sidebarSplitDropTarget).toContain("getSidebarSplitDropSourceFromEvent");
    expect(sidebarContextMenusHook).toContain("useContextMenuDismissal");
    expect(anchoredContextMenuHook).toContain("useContextMenuDismissal");
    expect(workspaceStrip).not.toContain('from "../tabs/SidebarMenuItem"');
    expect(workspaceStrip).not.toContain("tab-context-menu-separator");
    expect(workspaceStrip).toContain("sidebar-menu-field");
    expect(workspaceStrip).toContain("sidebar-menu-swatch");
    expect(workspaceStrip).not.toContain("workspace-menu-field");
    expect(workspaceStrip).not.toContain("workspace-menu-swatch");
    expect(tabGroupContextMenu).toContain("sidebar-menu-field");
    expect(tabGroupContextMenu).toContain("sidebar-menu-swatch");
    expect(tabContextMenu).toContain("<SidebarMenuSurface");
    expect(quickEntryContextMenu).toContain("<SidebarMenuSurface");
    expect(closedTabContextMenu).toContain("<SidebarMenuSurface");
    expect(tabGroupContextMenu).toContain("<SidebarMenuSurface");
    expect(workspaceStrip).toContain("<SidebarMenuSurface");
    for (const source of [tabContextMenu, quickEntryContextMenu, closedTabContextMenu, tabGroupContextMenu, workspaceStrip]) {
      expect(source).not.toContain("useMenuInitialFocus");
      expect(source).not.toContain("handleMenuKeyboardNavigation");
    }
    expect(workspaceStrip).not.toContain("window.addEventListener(\"click\"");
    expect(workspaceStrip).not.toContain("window.addEventListener(\"blur\"");
    expect(sidebarContextMenusHook).not.toContain("window.addEventListener(\"click\"");
    expect(anchoredContextMenuHook).not.toContain("window.addEventListener(\"click\"");
    expect(tabGroupContextMenu).not.toContain("tab-group-menu-field");
    expect(tabGroupContextMenu).not.toContain("tab-group-menu-swatch");
    expect(sidebarMenuCss).toContain(".sidebar-menu-surface");
    expect(sidebarMenuCss).toContain(".sidebar-menu-field");
    expect(sidebarMenuCss).toContain(".sidebar-menu-surface .sidebar-menu-swatch");
    expect(readFileSync(join(root, "src/renderer/styles/sidebar-action-hints.css"), "utf8")).toContain('[data-sidebar-modifier-hint="true"]');
    expect(readFileSync(join(root, "src/renderer/styles/sidebar.css"), "utf8")).toContain('[data-sidebar-tab-status-badge="true"]');
    expect(tabContextMenuCss).not.toContain("box-shadow: 0 18px 48px");
    expect(workspaceCss).not.toContain("box-shadow: 0 18px 48px");
    expect(tabContextMenuCss).not.toContain("background: #1f2630");
    expect(workspaceCss).not.toContain("background: #1f2630");
  });
});
