import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = join(__dirname, "..");

describe("sidebar component structure", () => {
  it("keeps cross-section sidebar menu chrome in the common component layer", () => {
    const commonMenuItemPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarMenuItem.tsx");
    const commonMenuSurfacePath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarMenuSurface.tsx");
    const commonModifierHintsPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarModifierActionHints.tsx");
    const commonTabStatusBadgesPath = join(root, "src/renderer/surfaces/sidebar/components/common/SidebarTabStatusBadges.tsx");
    const menuDismissalPath = join(root, "src/renderer/common/context-menu/menuDismissal.ts");
    const oldTabsMenuItemPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarMenuItem.tsx");
    const oldTabsStatusBadgesPath = join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarTabStatusBadges.tsx");
    const sidebarMenuCssPath = join(root, "src/renderer/styles/sidebar-menu.css");
    const stylesEntry = readFileSync(join(root, "src/renderer/styles.css"), "utf8");
    const commonMenuItem = readFileSync(commonMenuItemPath, "utf8");
    const commonMenuSurface = readFileSync(commonMenuSurfacePath, "utf8");
    const commonModifierHints = readFileSync(commonModifierHintsPath, "utf8");
    const commonTabStatusBadges = readFileSync(commonTabStatusBadgesPath, "utf8");
    const menuDismissal = readFileSync(menuDismissalPath, "utf8");
    const workspaceStrip = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/workspaces/WorkspaceStrip.tsx"), "utf8");
    const sidebarItemActionHints = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/SidebarItemActionHints.tsx"), "utf8");
    const sidebarSearchBox = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/chrome/SidebarSearchBox.tsx"), "utf8");
    const sidebarAddress = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/chrome/SidebarAddress.tsx"), "utf8");
    const sidebarContextMenusHook = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/useSidebarContextMenus.ts"), "utf8");
    const anchoredContextMenuHook = readFileSync(join(root, "src/renderer/common/context-menu/useAnchoredContextMenu.ts"), "utf8");
    const tabGroupContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/TabGroupContextMenu.tsx"), "utf8");
    const tabContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/TabContextMenu.tsx"), "utf8");
    const quickEntryContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/QuickEntryContextMenu.tsx"), "utf8");
    const closedTabContextMenu = readFileSync(join(root, "src/renderer/surfaces/sidebar/components/tabs/ClosedTabContextMenu.tsx"), "utf8");
    const sidebarMenuCss = readFileSync(sidebarMenuCssPath, "utf8");
    const workspaceCss = readFileSync(join(root, "src/renderer/styles/sidebar-workspaces.css"), "utf8");
    const tabContextMenuCss = readFileSync(join(root, "src/renderer/styles/sidebar-context-menu.css"), "utf8");

    expect(existsSync(commonMenuItemPath)).toBe(true);
    expect(existsSync(commonMenuSurfacePath)).toBe(true);
    expect(existsSync(commonModifierHintsPath)).toBe(true);
    expect(existsSync(commonTabStatusBadgesPath)).toBe(true);
    expect(existsSync(menuDismissalPath)).toBe(true);
    expect(existsSync(oldTabsMenuItemPath)).toBe(false);
    expect(existsSync(oldTabsStatusBadgesPath)).toBe(false);
    expect(existsSync(sidebarMenuCssPath)).toBe(true);
    expect(stylesEntry).toContain('@import "./styles/sidebar-menu.css";');
    expect(commonMenuItem).toContain("SidebarMenuSeparator");
    expect(commonMenuItem).not.toContain("tab-context-menu-separator");
    expect(commonMenuSurface).toContain("useMenuInitialFocus");
    expect(commonMenuSurface).toContain("handleMenuKeyboardNavigation");
    expect(commonMenuSurface).toContain('role="menu"');
    expect(commonMenuSurface).toContain("event.stopPropagation()");
    expect(commonModifierHints).toContain("FiEye");
    expect(commonModifierHints).toContain("FiColumns");
    expect(commonModifierHints).toContain("getModifierActionHintsLabel");
    expect(commonModifierHints).toContain("data-sidebar-modifier-hints");
    expect(commonModifierHints).toContain("data-sidebar-modifier-hint");
    expect(commonTabStatusBadges).toContain("data-sidebar-tab-status-badges");
    expect(commonTabStatusBadges).toContain("data-sidebar-tab-status-badge");
    expect(menuDismissal).toContain("useContextMenuDismissal");
    expect(menuDismissal).toContain("useRef");
    expect(menuDismissal).toContain("restoreFocus: false");
    expect(menuDismissal).toContain("window.addEventListener(\"scroll\"");
    expect(workspaceStrip).toContain('from "../common/SidebarMenuItem"');
    expect(workspaceStrip).toContain('from "../common/SidebarMenuSurface"');
    expect(workspaceStrip).toContain("useContextMenuDismissal");
    expect(sidebarItemActionHints).toContain("SidebarModifierActionHints");
    expect(sidebarSearchBox).toContain("SidebarModifierActionHints");
    expect(sidebarAddress).toContain("SidebarModifierActionHints");
    expect(sidebarSearchBox).not.toContain("FiEye");
    expect(sidebarSearchBox).not.toContain("FiColumns");
    expect(sidebarAddress).not.toContain("FiEye");
    expect(sidebarAddress).not.toContain("FiColumns");
    expect(sidebarContextMenusHook).toContain("useContextMenuDismissal");
    expect(anchoredContextMenuHook).toContain("useContextMenuDismissal");
    expect(workspaceStrip).not.toContain('from "../tabs/SidebarMenuItem"');
    expect(workspaceStrip).not.toContain("tab-context-menu-separator");
    expect(workspaceStrip).toContain("sidebar-menu-field");
    expect(workspaceStrip).toContain("sidebar-menu-swatch");
    expect(workspaceStrip).not.toContain("workspace-menu-field");
    expect(workspaceStrip).not.toContain("workspace-menu-swatch");
    expect(tabGroupContextMenu).toContain("sidebar-menu-field");
    expect(tabGroupContextMenu).toContain("sidebar-menu-swatch");
    expect(tabContextMenu).toContain("<SidebarMenuSurface");
    expect(quickEntryContextMenu).toContain("<SidebarMenuSurface");
    expect(closedTabContextMenu).toContain("<SidebarMenuSurface");
    expect(tabGroupContextMenu).toContain("<SidebarMenuSurface");
    expect(workspaceStrip).toContain("<SidebarMenuSurface");
    for (const source of [tabContextMenu, quickEntryContextMenu, closedTabContextMenu, tabGroupContextMenu, workspaceStrip]) {
      expect(source).not.toContain("useMenuInitialFocus");
      expect(source).not.toContain("handleMenuKeyboardNavigation");
    }
    expect(workspaceStrip).not.toContain("window.addEventListener(\"click\"");
    expect(workspaceStrip).not.toContain("window.addEventListener(\"blur\"");
    expect(sidebarContextMenusHook).not.toContain("window.addEventListener(\"click\"");
    expect(anchoredContextMenuHook).not.toContain("window.addEventListener(\"click\"");
    expect(tabGroupContextMenu).not.toContain("tab-group-menu-field");
    expect(tabGroupContextMenu).not.toContain("tab-group-menu-swatch");
    expect(sidebarMenuCss).toContain(".sidebar-menu-surface");
    expect(sidebarMenuCss).toContain(".sidebar-menu-field");
    expect(sidebarMenuCss).toContain(".sidebar-menu-surface .sidebar-menu-swatch");
    expect(readFileSync(join(root, "src/renderer/styles/sidebar-action-hints.css"), "utf8")).toContain('[data-sidebar-modifier-hint="true"]');
    expect(readFileSync(join(root, "src/renderer/styles/sidebar.css"), "utf8")).toContain('[data-sidebar-tab-status-badge="true"]');
    expect(tabContextMenuCss).not.toContain("box-shadow: 0 18px 48px");
    expect(workspaceCss).not.toContain("box-shadow: 0 18px 48px");
    expect(tabContextMenuCss).not.toContain("background: #1f2630");
    expect(workspaceCss).not.toContain("background: #1f2630");
  });
});
