# Copyright 2025 The Astra Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui/views/views.gni")

component("astra_history_page_views") {
  sources = [
    "astra_history_page_model.cc",
    "astra_history_page_model.h",
    "astra_history_page_view.cc",
    "astra_history_page_view.h",
  ]

  defines = [ "ASTRA_HISTORY_PAGE_VIEWS_IMPLEMENTATION" ]

  deps = [
    "//base",
    "//base:i18n",
    "//skia",
    "//ui/base",
    "//ui/color",
    "//ui/events",
    "//ui/gfx",
    "//ui/gfx:geometry_skia",
    "//ui/views",
    "//ui/views/controls",
    "//ui/views/controls/button",
    "//ui/views/controls/textfield",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "astra_history_page_views_unittest.cc",
  ]

  deps = [
    ":astra_history_page_views",
    "//base",
    "//base/test:test_support",
    "//testing/gtest",
    "//ui/views:views_test_support",
  ]
}
