import type { BrowserSettings, SplitLayout } from "../../../domain/browser";
import type { WebviewAction } from "../../../types/browser-ui";

export interface Command {
  title: string;
  subtitle: string;
  run: () => void;
  runInSplit?: () => void;
  runPreview?: () => void;
  shortcut?: string;
}

export interface CommandActions {
  addWorkspace: () => void;
  clearBrowsingData: () => void;
  clearHistory: () => void;
  clearWorkspaceBrowsingData: (workspaceId: string) => void;
  assignTabToGroup: (tabId: string, groupId: string) => void;
  closeActiveTab: () => void;
  closeOtherTabs: (tabId?: string) => void;
  closeTabsToLeft: (tabId?: string) => void;
  closeTabsToRight: (tabId?: string) => void;
  copyText: (text: string) => void;
  deleteWorkspace: (workspaceId: string) => void;
  duplicateActiveTab: () => void;
  fillSplitView: () => void;
  focusAddressBar: () => void;
  focusSplitPane: (tabId: string) => void;
  groupActiveTab: () => void;
  groupTab: (tabId: string) => void;
  moveTabToWorkspace: (tabId: string, workspaceId: string) => void;
  navigateActiveTab: (url: string) => void;
  newIncognitoWindow: () => void;
  openGlance: (url: string, title?: string) => void;
  openFind: () => void;
  peekCompactChrome: () => void;
  peekCompactSidebar: () => void;
  peekCompactToolbar: () => void;
  openTabInSplit: (tabId: string) => void;
  openUrlInSplit: (url: string, title?: string) => void;
  newTab: () => void;
  openUrlInActiveWorkspace: (url: string, title?: string) => void;
  restoreClosedTab: (closedIndex: number) => void;
  restoreLastClosedTab: () => void;
  runWebviewAction: (action: WebviewAction) => void;
  selectAdjacentTab: (direction: 1 | -1) => void;
  selectTab: (tabId: string) => void;
  setSplitLayout: (layout: SplitLayout) => void;
  resetActiveTabZoom: () => void;
  sleepInactiveTabs: () => void;
  sleepTab: (tabId: string) => void;
  switchWorkspace: (workspaceId: string) => void;
  toggleActiveDevTools: () => void;
  toggleActiveTabFavorite: () => void;
  toggleActiveTabEssential: () => void;
  toggleActiveTabMuted: () => void;
  toggleActiveTabPinned: () => void;
  toggleActivePictureInPicture?: () => Promise<unknown>;
  toggleCompactMode: () => void;
  toggleFloatingSidebar: () => void;
  toggleFloatingToolbar: () => void;
  toggleApplicationDevTools: () => void;
  toggleTabGroupCollapsed: (groupId: string) => void;
  toggleSidebar: () => void;
  toggleSplitMode: () => void;
  ungroupActiveTab: () => void;
  ungroupTab: (tabId: string) => void;
  updateSettings: (patch: Partial<BrowserSettings>) => void;
  zoomIn: () => void;
  zoomOut: () => void;
}
