// Copyright 2026 The Astra Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Generated-style resource header for Astra resources.
// =========================================================================
//
// NOTE: In a full Chromium build, this file is GENERATED by GRIT from
// astra_resources.grd and astra_strings.grdp.  This file is maintained
// manually in the overlay repo so that C++ code can reference resource
// IDs without running grit.
//
// When adding or removing resources:
//   1. Update astra_resources.grd / astra_strings.grdp
//   2. Update this header to match
//
// Chromium owner: tools/grit/ (resource compiler)
// Patch point: astra/app/resources/astra_resources.grd
// =========================================================================
//
// Resource ID numbering:
//   - String resources (IDS_*) start at 30000
//   - Structure resources (IDR_*) start at 50000
//   - These ranges are chosen to avoid collisions with Chromium's built-in
//     resources, which occupy lower ranges.
//   - TODO(astra): Coordinate final resource ID ranges with the Chromium
//     resource ID allocation scheme (tools/gritsettings/resource_ids).
//     In production builds, GRIT will assign IDs automatically.
// =========================================================================

#ifndef ASTRA_APP_RESOURCES_ASTRA_RESOURCES_H_
#define ASTRA_APP_RESOURCES_ASTRA_RESOURCES_H_

// =========================================================================
// String resources (IDS_*)
// =========================================================================
// Start of range: 30000

#define IDS_ASTRA_PRODUCT_NAME 30000
#define IDS_ASTRA_SHORT_PRODUCT_NAME 30001
#define IDS_ASTRA_COMPANY_NAME 30002

// New tab page strings
#define IDS_ASTRA_NEW_TAB_TITLE 30100
#define IDS_ASTRA_NTP_WORKSPACES_TITLE 30101
#define IDS_ASTRA_NTP_NEW_WORKSPACE_BUTTON 30102
#define IDS_ASTRA_NTP_MOST_VISITED_TITLE 30103
#define IDS_ASTRA_NTP_RECENTLY_VISITED_TITLE 30104
#define IDS_ASTRA_NTP_NO_SHORTCUTS_TEXT 30105
#define IDS_ASTRA_NTP_ADD_SHORTCUT 30106
#define IDS_ASTRA_NTP_TAB_COUNT 30107

// Sidebar strings
#define IDS_ASTRA_SIDEBAR_TITLE 30200
#define IDS_ASTRA_SIDEBAR_NEW_WORKSPACE 30201

// Settings strings
#define IDS_ASTRA_SETTINGS_TITLE 30300
#define IDS_ASTRA_SETTINGS_GENERAL 30301
#define IDS_ASTRA_SETTINGS_SIDEBAR 30302
#define IDS_ASTRA_SETTINGS_WORKSPACES 30303
#define IDS_ASTRA_SETTINGS_FOCUS_MODE 30304
#define IDS_ASTRA_SETTINGS_APPEARANCE 30305
#define IDS_ASTRA_SETTINGS_STARTUP_BEHAVIOR 30306
#define IDS_ASTRA_SETTINGS_STARTUP_CONTINUE 30307
#define IDS_ASTRA_SETTINGS_STARTUP_NEWTAB 30308
#define IDS_ASTRA_SETTINGS_STARTUP_SPECIFIC 30309
#define IDS_ASTRA_SETTINGS_DEFAULT_SEARCH 30310
#define IDS_ASTRA_SETTINGS_SIDEBAR_ENABLED 30311
#define IDS_ASTRA_SETTINGS_SIDEBAR_POSITION 30312
#define IDS_ASTRA_SETTINGS_SIDEBAR_WIDTH 30313
#define IDS_ASTRA_SETTINGS_SIDEBAR_AUTO_HIDE 30314
#define IDS_ASTRA_SETTINGS_DEFAULT_WORKSPACE 30315
#define IDS_ASTRA_SETTINGS_FOCUS_DURATION 30316
#define IDS_ASTRA_SETTINGS_FOCUS_SOUND 30317
#define IDS_ASTRA_SETTINGS_BLOCKED_SITES 30318
#define IDS_ASTRA_SETTINGS_THEME 30319
#define IDS_ASTRA_SETTINGS_ACCENT_COLOR 30320
#define IDS_ASTRA_SETTINGS_SYSTEM_THEME 30321
#define IDS_ASTRA_SETTINGS_COMPACT_MODE 30322
#define IDS_ASTRA_SETTINGS_SAVED 30323
#define IDS_ASTRA_SETTINGS_ADD_WORKSPACE 30324
#define IDS_ASTRA_SETTINGS_ACCENT_PRESETS 30325

// Recently closed (NTP)
#define IDS_ASTRA_NTP_RECENTLY_CLOSED_TITLE 30120
#define IDS_ASTRA_NTP_RESTORE_LAST 30121
#define IDS_ASTRA_NTP_NO_RECENTLY_CLOSED 30122

// =========================================================================
// Structure / binary resources (IDR_*)
// =========================================================================
// Start of range: 50000

// New tab page WebUI resources
#define IDR_ASTRA_NEW_TAB_HTML 50000
#define IDR_ASTRA_NEW_TAB_CSS  50001
#define IDR_ASTRA_NEW_TAB_JS   50002

// Settings page WebUI resources
#define IDR_ASTRA_SETTINGS_HTML 50010
#define IDR_ASTRA_SETTINGS_CSS  50011
#define IDR_ASTRA_SETTINGS_JS   50012

// TODO(astra): Add icon resource IDs when icon assets are added.
//   IDR_ASTRA_APP_ICON_16
//   IDR_ASTRA_APP_ICON_32
//   IDR_ASTRA_APP_ICON_48
//   IDR_ASTRA_APP_ICON_128
//   IDR_ASTRA_APP_ICON_256
//   IDR_ASTRA_APP_ICON_512
//   IDR_ASTRA_SIDEBAR_WORKSPACE_20DP
//   etc.

#endif  // ASTRA_APP_RESOURCES_ASTRA_RESOURCES_H_
