export const shortcutLabels = {
  back: "Alt+Left / Ctrl/Cmd+[",
  closeTab: "Ctrl/Cmd+W",
  devTools: "F12 / Ctrl/Cmd+Shift+I",
  downloads: "Ctrl/Cmd+Shift+Y",
  favorite: "Ctrl/Cmd+D",
  find: "Ctrl/Cmd+F",
  focusAddress: "Ctrl/Cmd+L",
  forward: "Alt+Right / Ctrl/Cmd+]",
  hardReload: "Ctrl/Cmd+Shift+R",
  history: "Ctrl/Cmd+H",
  mute: "Ctrl/Cmd+M",
  newTab: "Ctrl/Cmd+T",
  nextTab: "Ctrl/Cmd+Tab",
  previousTab: "Ctrl/Cmd+Shift+Tab",
  reload: "Ctrl/Cmd+R",
  resetZoom: "Ctrl/Cmd+0",
  restoreClosedTab: "Ctrl/Cmd+Shift+T",
  splitGrid: "Ctrl/Cmd+Alt+G",
  splitHorizontal: "Ctrl/Cmd+Alt+H",
  splitToggle: "Ctrl/Cmd+\\",
  splitVertical: "Ctrl/Cmd+Alt+V",
  toggleCompactMode: "Ctrl/Cmd+Alt+C",
  toggleFloatingSidebar: "Ctrl/Cmd+Alt+S",
  toggleFloatingToolbar: "Ctrl/Cmd+Alt+T",
  toggleSidebar: "Alt+B",
  unsplitAll: "Ctrl/Cmd+Alt+U",
  zoomIn: "Ctrl/Cmd++",
  zoomOut: "Ctrl/Cmd+-"
} as const;
