# Copyright 2025 The Astra Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ui/views/views.gni")

component("astra_downloads_views") {
  sources = [
    "astra_downloads_bubble_item_view.cc",
    "astra_downloads_bubble_item_view.h",
    "astra_downloads_bubble_model.cc",
    "astra_downloads_bubble_model.h",
    "astra_downloads_bubble_view.cc",
    "astra_downloads_bubble_view.h",
    "astra_downloads_toolbar_button.cc",
    "astra_downloads_toolbar_button.h",
  ]

  defines = [ "ASTRA_DOWNLOADS_VIEWS_IMPLEMENTATION" ]

  deps = [
    "//astra/browser:astra_browser_services",
    "//base",
    "//skia",
    "//ui/base",
    "//ui/gfx",
    "//ui/views",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    # TODO(astra): Add unit tests for downloads bubble views.
  ]

  deps = [
    ":astra_downloads_views",
    "//base",
    "//testing/gtest",
    "//ui/views",
  ]
}
