export { updateBrowserState } from "./browser/updateState";
export {
  clearHistory,
  clearBrowsingData,
  clearWorkspaceBrowsingData,
  navigateActiveTab,
  openUrlInActiveWorkspace,
  recordHistory,
  removeHistoryEntry,
  upsertDownload
} from "./browsing/actions";
export {
  clearSitePermissionRule,
  clearSitePermissionRulesForOrigin,
  setSitePermission,
  updateSettings
} from "./permissions/settingsActions";
export {
  addTab,
  assignTabToGroup,
  closeActiveTab,
  closeOtherTabs,
  closeTabGroup,
  closeTabsToLeft,
  closeTabsToRight,
  closeTab,
  addTabToFavorites,
  duplicateActiveTab,
  duplicateTab,
  duplicateTabGroup,
  fillSplitView,
  focusSplitPane,
  groupActiveTab,
  groupTab,
  groupTabsTogether,
  moveTabToWorkspace,
  moveTabGroupToWorkspace,
  moveTabToFavoritePosition,
  moveTabToFolderEnd,
  moveTabToFolderPosition,
  newTabInGroup,
  openTabInSplit,
  openUrlInSplit,
  removeTabFromSplit,
  removeEssential,
  moveWorkspaceFavoriteToWorkspace,
  removeWorkspaceFavorite,
  reorderEssential,
  reorderTabGroup,
  reorderWorkspaceFavorite,
  reorderTab,
  resetActiveTabZoom,
  restoreClosedTab,
  restoreClosedTabToWorkspace,
  restoreLastClosedTab,
  selectAdjacentTab,
  selectTab,
  setActiveTabZoom,
  setWorkspaceSplitLayout,
  sleepIdleTabs,
  sleepInactiveTabs,
  sleepTabGroup,
  sleepTab,
  stepActiveTabZoom,
  toggleActiveTabFavorite,
  toggleActiveTabEssential,
  toggleActiveTabMuted,
  toggleActiveTabPinned,
  toggleTabEssential,
  toggleTabFavorite,
  toggleTabGroupCollapsed,
  toggleTabMuted,
  toggleTabPinned,
  toggleSplitMode,
  ungroupActiveTab,
  ungroupTab,
  ungroupTabGroup,
  updateTabGroup,
  updateTab,
  type TabFolder,
  type TabDropPlacement
} from "./tabs";
export {
  addWorkspace,
  deleteWorkspace,
  moveTabGroupToNewWorkspace,
  moveTabToNewWorkspace,
  moveWorkspaceFavoriteToNewWorkspace,
  reorderWorkspace,
  restoreClosedTabToNewWorkspace,
  switchWorkspace,
  updateWorkspaceById,
  updateWorkspace,
  type WorkspaceDropPlacement
} from "./workspaces/actions";
