export { updateBrowserState } from "./browser/updateState";
export {
  clearHistory,
  clearBrowsingData,
  clearWorkspaceBrowsingData,
  navigateActiveTab,
  openUrlInActiveWorkspace,
  recordHistory,
  removeDownload,
  removeHistoryEntry,
  upsertDownload
} from "./browsing/actions";
export {
  clearAllPerOriginZoomSettings,
  clearPerOriginZoom,
  clearSitePermissionRule,
  clearSitePermissionRulesForOrigin,
  removeAddress,
  removePassword,
  removePaymentMethod,
  setIncognitoMode,
  setPerOriginZoom,
  setSitePermission,
  touchPasswordUsed,
  updateReaderSettings,
  updateSettings,
  updateTranslationSettings,
  upsertAddress,
  upsertPassword,
  upsertPaymentMethod,
  /* ===== M2.1 Profile / Extension / Reset ===== */
  addProfile,
  removeProfile,
  switchProfile,
  addExtension,
  removeExtension,
  toggleExtension,
  resetSettings,
  clearAllDownloads
} from "./permissions/settingsActions";
export {
  addTab,
  assignTabToGroup,
  closeActiveTab,
  closeOtherTabs,
  closeTabGroup,
  closeTabsToLeft,
  closeTabsToRight,
  closeTab,
  addTabToFavorites,
  duplicateActiveTab,
  duplicateTab,
  duplicateTabGroup,
  fillSplitView,
  focusSplitPane,
  groupActiveTab,
  groupTab,
  groupTabsTogether,
  moveTabToWorkspace,
  moveTabGroupToWorkspace,
  moveTabToFavoritePosition,
  moveTabToFolderEnd,
  moveTabToFolderPosition,
  newTabInGroup,
  openTabInSplit,
  openUrlInSplit,
  removeTabFromSplit,
  removeEssential,
  moveWorkspaceFavoriteToWorkspace,
  removeWorkspaceFavorite,
  reorderEssential,
  reorderTabGroup,
  reorderWorkspaceFavorite,
  reorderTab,
  resetActiveTabZoom,
  restoreClosedTab,
  restoreClosedTabToWorkspace,
  restoreLastClosedTab,
  selectAdjacentTab,
  selectTab,
  selectSplitTab,
  setActiveTabZoom,
  setWorkspaceSplitLayout,
  sleepIdleTabs,
  sleepInactiveTabs,
  sleepTabGroup,
  sleepTab,
  stepActiveTabZoom,
  toggleActiveTabFavorite,
  toggleActiveTabEssential,
  toggleActiveTabMuted,
  toggleActiveTabPinned,
  toggleTabEssential,
  toggleTabFavorite,
  toggleTabGroupCollapsed,
  toggleTabMuted,
  toggleTabPinned,
  toggleSplitMode,
  swapSplitPanes,
  toggleSplitPaneSide,
  setSplitPaneSide,
  ungroupActiveTab,
  ungroupTab,
  ungroupTabGroup,
  updateTabGroup,
  updateTab,
  type TabFolder,
  type TabDropPlacement
} from "./tabs";
export {
  addWorkspace,
  deleteWorkspace,
  moveTabGroupToNewWorkspace,
  moveTabToNewWorkspace,
  moveWorkspaceFavoriteToNewWorkspace,
  reorderWorkspace,
  restoreClosedTabToNewWorkspace,
  switchWorkspace,
  updateWorkspaceById,
  updateWorkspace,
  type WorkspaceDropPlacement
} from "./workspaces/actions";
